services:
  database:
    image: mysql:8.0
    container_name: mysqlcontainer
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: people_places_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: prod
      SERVICE_NAME: database
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: unless-stopped
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge